-- ============================================================
-- MIGRACIÓN: teams_data
-- Ejecutar en el SQL Editor de Supabase
-- ============================================================

CREATE TABLE IF NOT EXISTS teams_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base_name TEXT NOT NULL UNIQUE,
  color TEXT,
  youtube_id TEXT,
  youtube_patterns JSONB DEFAULT '[]'::jsonb,
  youtube_name TEXT,
  youtube_priority BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para búsqueda rápida por base_name
CREATE INDEX IF NOT EXISTS idx_teams_data_base_name ON teams_data (base_name);

-- ============================================================
-- DATOS COMPLETOS (colores + YouTube)
-- ============================================================

INSERT INTO teams_data (base_name, color, youtube_id, youtube_patterns, youtube_name, youtube_priority) VALUES
  ('OCISA',       '#36906D', 'UC9bIaWAOGv4hGkGgN-FDnhQ', '["logrono","logroño"]',                           'Ocisa Logroño',         false),
  ('AIDEAN',      '#E65900', 'UChXUSuJD-XCLjmFZUYcCtVg', '["aidean"]',                                    'Aidean ZKE',            false),
  ('AIXERROTA',   '#8B0135', NULL, NULL, NULL, NULL),
  ('ARMENTIA',    '#F46B27', NULL, NULL, NULL, NULL),
  ('ARIZMENDI',   '#8C2377', NULL, NULL, NULL, NULL),
  ('BERA BERA',   '#3173C7', 'UCs8IABn1087s4X_xrHCHbJQ', '["bera bera","berabera"]',                     'Bera Bera',             false),
  ('CARMELITAS',  '#0B87DD', NULL, NULL, NULL, NULL),
  ('DIOS',        '#55B9E1', 'UCxGbXULdYqJJTn97vBhK8cw', '["madre de dios","madi","deusto"]',            'Madre de Dios Deusto',  false),
  ('EGIBIDE',     '#80005D', NULL, NULL, NULL, NULL),
  ('EKIALDE',     '#5081D0', 'UCEeow14MIifOsTXS4uSCB5g', '["ekialde"]',                                   'Cafés Foronda Ekialde', false),
  ('FORTUNA',     '#FA6D28', NULL, NULL, NULL, NULL),
  ('GALDAKAO',    '#0277B7', 'UCheRHnoAnFsI7Ogd9xSYAFQ', '["galdakao"]',                                 'Galdakao',              false),
  ('GALLARTA',    '#008300', 'UCi0OUunq4dpoeIDnrRnKaiw', '["gallarta"]',                                  'Gallartaren Ahotsa',    false),
  ('GETXO',       '#8B0135', 'UCYHKUaL8kC4QDe5Cx7TgMyg', '["getxo"]',                                   'Getxo',                 true),
  ('HERNANI',     '#2F2F2F', NULL, NULL, NULL, NULL),
  ('HRV',         '#003261', NULL, NULL, NULL, NULL),
  ('JATORKIDE',   '#592e77', 'UCDv0NQL_EFWtPC3i5v_Drbw', '["jatorkide"]',                                'Jatorkide',             true),
  ('KOLDO',       '#EEE300', NULL, NULL, NULL, NULL),
  ('LEKEITIO',    '#EC990D', NULL, NULL, NULL, NULL),
  ('LOGROÑO',     '#941109', NULL, NULL, NULL, NULL),
  ('MARIANISTAS', '#E02512', NULL, NULL, NULL, NULL),
  ('MENDEBALDEA', '#743409', NULL, NULL, NULL, NULL),
  ('MERCEDARIAS', '#253769', NULL, NULL, NULL, NULL),
  ('NAVARVOLEY',  '#DF2F2F', 'UC_utcf6nsss9TBzw0IkTs2w', '["navar"]',                                   'Navarvoley',            false),
  ('OSTADAR',     '#7A5F38', NULL, NULL, NULL, NULL),
  ('OTSOKUMEAK',  '#515151', NULL, NULL, NULL, NULL),
  ('REKALDE',     '#032A75', NULL, NULL, NULL, NULL),
  ('SANTANDER',   '#C20E1A', NULL, NULL, NULL, NULL),
  ('SESTAO',      '#0D5427', 'UC0RH2gitr2hjNYHhCENpzLg', '["sestao"]',                                  'C.V.Sestao',            false),
  ('UNAMUNO',     NULL, NULL, NULL, NULL, NULL),
  ('ZABALGANA',   '#743409', NULL, NULL, NULL, NULL),
  ('TOLOBOLEI',   NULL, 'UC0e86MqCMbNFoJBCWbLyPxQ', '["tolobolei"]',                                   'Tolobolei',             false)
ON CONFLICT (base_name) DO NOTHING;

-- ============================================================
-- HABILITAR ROW LEVEL SECURITY (opcional pero recomendado)
-- ============================================================

ALTER TABLE teams_data ENABLE ROW LEVEL SECURITY;

-- Permitir SELECT al rol anónimo (necesario para la app cliente)
CREATE POLICY "Allow public SELECT" ON teams_data
  FOR SELECT USING (true);

-- ============================================================
-- VERIFICACIÓN
-- ============================================================

SELECT COUNT(*) AS total_teams FROM teams_data;
SELECT base_name, color FROM teams_data WHERE color IS NOT NULL ORDER BY base_name;
SELECT base_name, youtube_name FROM teams_data WHERE youtube_id IS NOT NULL ORDER BY base_name;
